.\" To view:
.\" man -l hgview.1
.TH HGQV 1
.SH NAME
hgqv \- A revision history browser for mercurial repositories
.SH SYNOPSIS
.ll +8
.B hgqv
.RB [ \-h ]
.RB [ \-R repo ]
.ll -8
.SH DESCRIPTION
.B hgqv
is a GUI application usually invoked from the command line. The simplest 
way to use it is to install it as a hg extension. Alternatively, it can
be used as a standalone application by calling it from a mercurial repository.
.SH OPTIONS
.HP
\fB\-R\fR \fIREPO\fR, \fB--repository\fR=\fIREPO\fR
.IP
Specify the repository to use on the command line instead of using the
current working directory.
.SH FILES
.I $HOME/.hgrc
.RS
hg configuration, section [qtview]
.RE
.I $HOME/.hgusers
.RS
users configuration file (allow to define aliases and to affect a color to a user)
.RE
.I $REPO/.hg/hgrc
.RS
repository local configuration file
.SH SEE ALSO
hg(1), gitk(1)
.PP
